name: erlang-analyzer
spec-version: 0.36.0

library:
  source-dirs: src
  dependencies:
  - base >= 4.17 && < 5
  - containers
  - extra
  - mtl
  - array
  - megaparsec
  - maf2-syntax
  build-tools:
  - alex 
  - happy


executable:
  source-dirs: app
  main: Main.hs
  dependencies:
    - optparse-applicative
    - base >= 4.17 && < 5
    - erlang-analyzer
    - pretty-simple

