name: erlang-analyzer
spec-version: 0.36.0

library:
  source-dirs: src
  dependencies:
  - base >= 4.17 && < 5
  - containers
  - extra
  - mtl
  - array
  - megaparsec
  - maf2-syntax
  build-tools:
  - alex 
  - happy
