name:                maf2-syntax
version:             0.1.0.0
github:              "softwarelanguageslab/maf2-syntax"
license:             BSD-3-Clause
author:              "Software Languages Lab - VUB"
maintainer:          "example@example.com"
copyright:           "2023 Author name here"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/maf2-syntax#readme>

extra-source-files:
  - preludes/*

dependencies:
- base >= 4.17 && < 5
- megaparsec >= 9.7 && < 9.8
- array >= 0.5 && <0.6
- language-python
- mtl >= 2.3 && <2.4
- transformers
- containers
- parsec >= 3.1
- data-default
- file-embed
- template-haskell
- process
- deepseq
- lens
- directory
- filepath
- extra
- parser-combinators

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  exposed-modules:
    - Syntax 
    - Syntax.Ide
    - Syntax.Span 
    - Syntax.FV
    - Syntax.Python
    - Syntax.Python.AST
    - Syntax.Scheme
    - Syntax.Scheme.AST
    - Syntax.Scheme.Undefiner
    - Syntax.Scheme.Actor
    - Syntax.Scheme.Parser
    - Syntax.Scheme.Prelude
    - Syntax.Erlang
    - Syntax.Erlang.AST
    - Syntax.Erlang.Parser
    - Syntax.Erlang.Compiler
    - Syntax.Erlang.Overloader
    - Syntax.Erlang.Qualifier
    - Syntax.Erlang.Preluder
    - Syntax.CoreErlang
  verbatim:
      build-tools:
        happy


default-extensions:
  - StandaloneDeriving
  - KindSignatures
  - TypeFamilies
  - DeriveGeneric
  - TupleSections
  - NamedFieldPuns
  - RankNTypes

tests:
  maf2-syntax-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - maf2-syntax
