name:                maf2-syntax
version:             0.1.0.0
github:              "githubuser/maf2-syntax"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2023 Author name here"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/maf2-syntax#readme>

dependencies:
- base >= 4.7 && < 5
- language-python
- mtl
- containers
- hashable
- parsec >= 3.1
- data-default

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  exposed-modules:
    - Syntax.Python
    - Syntax.Python.AST
    - Syntax.Scheme
    - Syntax.Scheme.AST
    - Syntax.Scheme.Undefiner
    - Syntax.Erlang.Parser

default-extensions:
  - StandaloneDeriving
  - KindSignatures
  - TypeFamilies
  - DeriveGeneric
  - TupleSections
  - NamedFieldPuns
  - RankNTypes

tests:
  maf2-syntax-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - maf2-syntax
