name:                maf2-domains
version:             0.1.0.0
github:              "softwarelanguageslab/maf-hs"
license:             BSD3
author:              "Software Languages Lab"
maintainer:          ""
copyright:           "2023 Software Languages Lab"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/maf2-domains#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- unordered-containers
- mtl
- transformers
- data-default
- extra
- maf2-syntax
- maf2-typelevel
- hashable

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  exposed-modules: 
    - Domain
    - Domain.Lattice
    - Domain.ConstantPropagation
    - Domain.Dictionary
    - Domain.Scheme
    - Domain.Scheme.Class
    - Domain.Scheme.Modular
    - Domain.Scheme.CPDomain
    - Domain.Actors
    - Domain.TopLifted
    - Domain.Python
    - Domain.Python.ClassDomain
    - Domain.Python.CPDomain
    - Control.Monad.Join
    - Control.Monad.DomainError
    - Data.DMap

default-extensions:
  - TypeFamilies
  - TupleSections
  - TemplateHaskell
  - NamedFieldPuns
  - TypeOperators
  - InstanceSigs
  - DeriveGeneric
  - TypeApplications
  - StandaloneDeriving
  - ScopedTypeVariables
  - DataKinds
  - MultiParamTypeClasses
  - FunctionalDependencies
  - GeneralizedNewtypeDeriving


tests:
  maf2-domains-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - maf2-domains
    - QuickCheck >= 2.14.2
    - hspec 
    - hspec-contrib
    - HUnit

