(letrec
  ((ping-behavior (behavior ()
                    ((ping (sender) 
                        ;; (print sender)
                        (send sender pong self) 
                        (become ping-behavior)))))
   (pong-behavior (behavior ()
                   ((pong (sender)
                        ;; (print 'pong)
                        (send sender ping self)
                        (become pong-behavior)))))
   (ping/c  (behavior/c (message/c 'ping (actor?) unspecified-recipient ping/cm)))
   (ping/cm (lambda (sender) 
              (ensures/c (message/c 'pong (actor?) 
                                    (specific-recipient sender)
                                    (lambda (sender)
                                      (ensures/c (message/c 'ping
                                                            (actor?)
                                                            (specific-recipient sender)
                                                            ping/cm))))))))

  (letrec ((ping (mon client server ping/c (spawn ping-behavior)))
           (pong (spawn pong-behavior)))
    (begin (send ping ping pong)
           (sleep 2)
           (wait-until-all-finished))))
