name: ase
version: 0.1


dependencies:
  - base >= 4.2
  - maf2-analysis
  - maf2-syntax
  - maf2-domains
  - maf2-scv
  - simpleactor
  - rio
  - mtl
  - random

ghc-options:
  - -O2
  - -optc-O3
  - -funfolding-use-threshold=32
  - -fspecialise-aggressively
  - -fexpose-all-unfoldings

default-extensions:
  - LambdaCase
  - TypeFamilies
  - FlexibleContexts
  - MultiParamTypeClasses
  - FunctionalDependencies
  - ConstraintKinds
  - TupleSections
  - GADTs

library:  
  source-dirs: src

executable:
  source-dirs: app
  main: Main.hs
  dependencies:
    - optparse-applicative
    - ase
  ghc-options:
  - -rtsopts
  - '"-with-rtsopts=-sstderr"'
