name:                simpleactor
version:             0.1.0.0
github:              "bramvdbogaerde/simplecc"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "bram@vdb.space"
copyright:           "2024 Bram Vandenbogaerde"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/interpreter#readme>

dependencies:
- base >= 4.7 && < 5
- hspec
- hspec-contrib
- deepseq
- rio
- singletons


ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -O3
- -fspecialise
- -fexpose-all-unfoldings
- -flate-dmd-anal
- -Wredundant-constraints

default-extensions:
  - ConstraintKinds
  - TypeFamilies
  - MultiParamTypeClasses
  - FlexibleContexts
  - FlexibleInstances
  - DataKinds
  - TypeOperators
  - GeneralizedNewtypeDeriving
  - TemplateHaskell
  - StandaloneKindSignatures
  - EmptyCase
  - GADTs
  - TypeApplications
  - TupleSections
  - RankNTypes
  - ScopedTypeVariables
  - FunctionalDependencies
  - StandaloneDeriving
  - RecordWildCards
  
library:
  source-dirs: src
  dependencies:
    - containers 
    - unordered-containers 
    - mtl
    - transformers
    - maf2-syntax
    - maf2-domains
    - maf2-analysis
    - maf2-scv
    - lens
    - concurrency
    - exceptions
    - process
    - layers-mtl
    - random

executables:
  simpleactor-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - containers
    - optparse-applicative
    - simpleactor
    - maf2-syntax
    - maf2-domains
    - maf2-analysis
    - filepath
    - time
    - timeit
    
tests:
  simpleactor-tests:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - simpleactor
    - maf2-analysis
