name: Analysis CI

on:
  push:
    branches: [ "main", "2cabal" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: haskell-actions/setup@v2
      with:
        ghc-version: '9.4.8'
        cabal-version: '3.10'
        ghcup-release-channel: 'https://raw.githubusercontent.com/haskell/ghcup-metadata/develop/ghcup-0.0.8.yaml'

    - name: Cache
      uses: actions/cache@v3
      env:
        cache-name: cache-cabal
      with:
        path: ~/.cabal
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Install dependencies
      working-directory: maf2-analysis
      run: cabal update && cabal install --overwrite-policy=always hspec-discover 
    - name: Build
      working-directory: maf2-analysis
      run: cabal build
    - name: Run tests
      working-directory: maf2-analysis
      run: cabal test --test-show-details=always --test-options="--color"
